### ISSUE TITLE
Did you guys use S6 layer or the S4 layer?

### ISSUE THREAD

**Issue by siddagra** [NVlabs/MambaVision#1]
I just had a tiny question. Did you guys use S6 layer or the S4 layer? Typically mamba itself uses S6 so I was wondering.

**Comment by ahatamiz** [comment]
Yes, we used S6 which has leverages the power of "selectivity". 

It would be interesting to try S4 as well at this point. But our main contribution is how to use Mamba for vision, in an efficient manner (throughput-wise) and still retain SOTA performance.

**Comment by siddagra** [comment]
Thanks for the information :)

Is the paper released anywhere? I found many papers that have similar names, but they don't seem to be from Nvidia and don't have the same name.

The reason I asked my original S4/S6 question was because of this section on the mamba page:
> No Free Lunch: Continuous-Discrete Spectrum. Structured SSMs were originally defined as discretizations of
continuous systems (1), and have had a strong inductive bias toward continuous-time data modalities such as perceptual
signals (e.g. audio, video). As discussed in Sections 3.1 and 3.5, the selection mechanism overcomes their weaknesses on
discrete modalities such as text and DNA; but this conversely can impede their performance on data that LTI SSMs excel
on. Our ablations on audio waveforms examine this tradeoff in more detail.

![image](https://github.com/user-attachments/assets/9222a0a3-44f8-4489-9e00-525869231a3e)

Hence, I thought it would be a good idea to try something with S4 or S5 instead since images are also more continuous data than text (which is what the Mamba S6 is designed for). You may try it out if you like; however, I am unsure how well it would work once you tokenise the patches, as they may be more discretised rather than continuous with that step. I would love to collaborate on some formulation that perhaps exploits this property if you are also interested.

**Comment by siddagra** [comment]
found the paper. probably best to also link it in the github :) https://arxiv.org/abs/2407.08083

**Comment by ahatamiz** [comment]
Hi @siddagra , thanks for the note. This is indeed an interesting avenue to further investigate. 

Images are still tokenized in our instance, but using S4 or S5 may actually be beneficial due to their continuous nature. 

Our goal in MambaVision was to create the foundation for models that use Mamba formulation but can be practical as well -- SOTA performance, fast throughput and no need for any more specialized kernels than the Mamba itself. 

These additions, such as investigating if S4 or S5 may work better should further propel this line of work.

Kind Regards
