### ISSUE TITLE
Why do you choose conv1d instead of conv2d?

### ISSUE THREAD

**Issue by yyNoBug** [NVlabs/MambaVision#3]
For vision tasks, does it make more sense to use 2D convolution?

**Comment by ahatamiz** [comment]
You are right in the sense that using 2D conv is more suitable for vision. But we made the decision to use conv1d since it has a better synergy with other MambaVision token mixer operations such as SSM. For example, working with features of size [B,N,C] no reshaping operation would be needed.

Lastly, stage 1 and 2 have conv2d which should incorporate inductive biases for vision tasks.

**Comment by yyNoBug** [comment]
Thank you!
